# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Navn')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=500, verbose_name='Fornavn')),
                ('family_name', models.CharField(max_length=500, verbose_name='Etternavn')),
                ('email', models.CharField(max_length=500, verbose_name='email')),
                ('mobile_phone', models.CharField(max_length=12, verbose_name='Mobilnummer')),
                ('work_phone', models.CharField(max_length=12, verbose_name='Jobbtelefon')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, verbose_name='Type')),
                ('info', models.CharField(max_length=500, verbose_name='Informasjon')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='backend.Department', verbose_name='Avdeling')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='backend.Person', verbose_name='Person')),
            ],
        ),
    ]
