# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobilnummer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Jobbtelefon'),
        ),
    ]
