# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170826_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['family_name', 'given_name']},
        ),
    ]
