# Service setup for development
version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  assets_bower_dev: {}
  assets_node_dev: {}

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tfk

  backend:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    links:
      - postgres:db
    environment:
      - USE_DOCKER=yes
      - DATABASE_WAIT=yes
      - DJANGO_SETTINGS_MODULE=settings.local
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "${APP_PORT}:8000"

  rproxy:
    build:
      context: ./compose/nginx
      dockerfile: ./Dockerfile-dev
    depends_on:
      - backend
      - frontend
    env_file:
      - .env
    links:
      - backend
      - frontend
    ports:
      - "${WEB_PORT}:80"

  frontend:
    build: ./compose/assets
    volumes:
      - ./frontend:/app
      - assets_bower_dev:/app/bower_components
      - assets_node_dev:/app/node_modules
    tmpfs:
      - /app/tmp
    env_file:
      - .env
    environment:
      - API_HOST=http://localhost:${WEB_PORT}
      - LIVERELOAD_PATH=assets/build/
    command: /watch.sh
